### ISSUE TITLE
epp() parameters hash not supported

### ISSUE THREAD

**Issue by pmuller** [deanwilson/puppet-lint-template_file_extension-check#3]
Hello

I like the idea of this plugin, but it looks like it doesn't support passing a parameters hash to the epp() function. I wrote a test case to ensure I haven't missed something (see #2), but unfortunately, as I don't have Ruby experience, I don't know how to fix it properly.

Thanks for your help!

**Comment by deanwilson** [comment]
Hi @pmuller,
  Thanks for spotting this and raising the issue, you're completely correct.

Also a big thank you to @seanmil for the fix and PR. 

Can either of you see an issue with https://github.com/deanwilson/puppet-lint-template_file_extension-check/pull/5 as an alternative solution that adds less code to the check? If I've missed something I'll happily merge https://github.com/deanwilson/puppet-lint-template_file_extension-check/pull/4 instead. I'll also update the changelog to add a thank you.

**Comment by seanmil** [comment]
No, I can't think of a reason not to use your solution in #5. Simple & clever, I like it. Thanks!

**Comment by deanwilson** [comment]
I've merged in #5, tagged the release and pushed to rubygems. Thank you both for your work on this.
